// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./../src/components/Button.vue')['default']
    Drawer: typeof import('./../src/components/Drawer.vue')['default']
    HistoryList: typeof import('./../src/components/HistoryList.vue')['default']
    M3u8Video: typeof import('./../src/components/M3u8Video.vue')['default']
    SearchInput: typeof import('./../src/components/SearchInput.vue')['default']
  }
}
